version: 2
before:
  hooks:
    - go generate
    - go test ./...
builds:
  - id: containerssh-agent
    binary: "containerssh-agent"
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - ids:
      - containerssh-agent
    format_overrides:
      - goos: windows
        formats:
          - zip
nfpms:
  - id: deb-package
    vendor: ContainerSSH
    homepage: https://containerssh.io
    maintainer: Janos Pasztor <handshake@containerssh.io>
    description: The guest agent for ContainerSSH, an SSH server that launches containers on demand.
    license: MIT
    package_name: containerssh-agent
    ids:
      - containerssh-agent
    formats:
      - deb
    bindir: /usr/bin
  - id: rpm-package
    vendor: ContainerSSH
    homepage: https://containerssh.io
    maintainer: Janos Pasztor <handshake@containerssh.io>
    description: The guest agent for ContainerSSH, an SSH server that launches containers on demand.
    license: MIT
    package_name: containerssh-agent
    ids:
      - containerssh-agent
    formats:
      - rpm
    bindir: /usr/bin
  - id: apk-package
    vendor: ContainerSSH
    homepage: https://containerssh.io
    maintainer: Janos Pasztor <handshake@containerssh.io>
    description: The guest agent for ContainerSSH, an SSH server that launches containers on demand.
    license: MIT
    package_name: containerssh-agent
    ids:
      - containerssh-agent
    formats:
      - apk
    bindir: /usr/bin
dockers:
  - image_templates:
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform linux/amd64"
    goarch: amd64
  - image_templates:
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "quay.io/arres/containerssh/agent:latest"
    image_templates:
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-amd64"
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-arm64"
  - name_template: "quay.io/arres/containerssh/agent:{{ .Tag }}"
    image_templates:
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-amd64"
      - "quay.io/arres/containerssh/agent:{{ .Tag }}-arm64"
source:
  enabled: true
  name_template: 'containerssh-agent-{{ .Version }}-source'
dist: build
release:
  github:
    owner: RockinRoel
    name: containerssh-agent
  prerelease: auto
  extra_files:
    - glob: LICENSE
